"""profile emails

Revision ID: 0ada5978a198
Revises: 787484ac7dd3
Create Date: 2025-11-23 23:13:27.145525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ada5978a198'
down_revision = '787484ac7dd3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('email', sa.String(), nullable=True))
    op.create_index(op.f('ix_profiles_email'), 'profiles', ['email'], unique=True)
    op.drop_index(op.f('ix_referrals_status'), table_name='referrals')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_referrals_status'), 'referrals', ['status'], unique=False)
    op.drop_index(op.f('ix_profiles_email'), table_name='profiles')
    op.drop_column('profiles', 'email')
    # ### end Alembic commands ###
