"""fix time default for sqlite compatibility

Revision ID: 21b428c1e57c
Revises: 7fce4ad94fc0
Create Date: 2025-11-19 22:59:28.626898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21b428c1e57c'
down_revision = '7fce4ad94fc0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
