"""add_admin_assignment

Revision ID: 46313761122a
Revises: 0ada5978a198
Create Date: 2025-12-29 05:26:15.797382

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '46313761122a'
down_revision = '0ada5978a198'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('assignment_config', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('referrals', sa.Column('assigned_admin_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_referrals_assigned_admin_id'), 'referrals', ['assigned_admin_id'], unique=False)
    op.create_foreign_key(None, 'referrals', 'profiles', ['assigned_admin_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'referrals', type_='foreignkey')
    op.drop_index(op.f('ix_referrals_assigned_admin_id'), table_name='referrals')
    op.drop_column('referrals', 'assigned_admin_id')
    op.drop_column('organizations', 'assignment_config')
    # ### end Alembic commands ###
