"""add invite email and null profile

Revision ID: 573df1460576
Revises: a0f6097c8f6f
Create Date: 2025-10-28 01:06:31.020486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '573df1460576'
down_revision = 'a0f6097c8f6f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization_members', sa.Column('invite_email', sa.String(), nullable=True))
    op.alter_column('organization_members', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_organization_members_invite_email'), 'organization_members', ['invite_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organization_members_invite_email'), table_name='organization_members')
    op.alter_column('organization_members', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('organization_members', 'invite_email')
    # ### end Alembic commands ###
