"""expand_profiles_and_organizations_settings

Revision ID: 7f93e92388df
Revises: cb4c5726f2f1
Create Date: 2025-11-19 17:28:45.420402

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7f93e92388df'
down_revision = 'cb4c5726f2f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Ensure the orgrole enum exists (it should from previous migrations)
    op.execute("""
        DO $$ BEGIN
            CREATE TYPE orgrole AS ENUM ('admin', 'secretary', 'staff', 'guardian', 'student');
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """)
    
    # Convert invitations.role from VARCHAR to orgrole enum using explicit cast
    op.execute("ALTER TABLE invitations ALTER COLUMN role TYPE orgrole USING role::orgrole")
    op.add_column('organizations', sa.Column('district_id', sa.UUID(), nullable=True))
    op.add_column('organizations', sa.Column('street_number', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('street_name', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('city', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('state', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('zip_code', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('office_extension', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('lower_grade', sa.Integer(), nullable=True))
    op.add_column('organizations', sa.Column('upper_grade', sa.Integer(), nullable=True))
    op.add_column('organizations', sa.Column('slug', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('preset_config', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('organizations', sa.Column('form_config', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('organizations', sa.Column('aeries_school_code', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('sis_source_id', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('sis_client_id', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('sis_client_secret', sa.String(), nullable=True))
    op.add_column('organizations', sa.Column('disclaimers', sa.Text(), nullable=True))
    op.add_column('organizations', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_organizations_aeries_school_code'), 'organizations', ['aeries_school_code'], unique=False)
    op.create_index(op.f('ix_organizations_sis_source_id'), 'organizations', ['sis_source_id'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.add_column('profiles', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('street_number', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('street_name', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('city', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('state', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('zip_code', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('country', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('preferred_language', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('grade_level', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('student_id', sa.String(), nullable=True))
    op.add_column('profiles', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('profiles', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.create_index(op.f('ix_profiles_student_id'), 'profiles', ['student_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_student_id'), table_name='profiles')
    op.drop_column('profiles', 'updated_at')
    op.drop_column('profiles', 'is_active')
    op.drop_column('profiles', 'student_id')
    op.drop_column('profiles', 'grade_level')
    op.drop_column('profiles', 'preferred_language')
    op.drop_column('profiles', 'country')
    op.drop_column('profiles', 'zip_code')
    op.drop_column('profiles', 'state')
    op.drop_column('profiles', 'city')
    op.drop_column('profiles', 'street_name')
    op.drop_column('profiles', 'street_number')
    op.drop_column('profiles', 'phone')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_sis_source_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_aeries_school_code'), table_name='organizations')
    op.drop_column('organizations', 'updated_at')
    op.drop_column('organizations', 'disclaimers')
    op.drop_column('organizations', 'sis_client_secret')
    op.drop_column('organizations', 'sis_client_id')
    op.drop_column('organizations', 'sis_source_id')
    op.drop_column('organizations', 'aeries_school_code')
    op.drop_column('organizations', 'form_config')
    op.drop_column('organizations', 'preset_config')
    op.drop_column('organizations', 'slug')
    op.drop_column('organizations', 'upper_grade')
    op.drop_column('organizations', 'lower_grade')
    op.drop_column('organizations', 'office_extension')
    op.drop_column('organizations', 'phone_number')
    op.drop_column('organizations', 'zip_code')
    op.drop_column('organizations', 'state')
    op.drop_column('organizations', 'city')
    op.drop_column('organizations', 'street_name')
    op.drop_column('organizations', 'street_number')
    op.drop_column('organizations', 'district_id')
    # Convert invitations.role back to VARCHAR for downgrade
    op.execute("ALTER TABLE invitations ALTER COLUMN role TYPE VARCHAR USING role::text")
    # ### end Alembic commands ###
