"""change_disclaimers_to_json

Revision ID: 7fce4ad94fc0
Revises: 7f93e92388df
Create Date: 2025-11-19 20:56:19.630080

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7fce4ad94fc0'
down_revision = '7f93e92388df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Convert disclaimers from TEXT to JSON using explicit cast
    # Handle NULL values and empty strings
    op.execute("""
        ALTER TABLE organizations 
        ALTER COLUMN disclaimers TYPE JSON 
        USING CASE 
            WHEN disclaimers IS NULL OR disclaimers = '' THEN NULL
            ELSE disclaimers::json
        END
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Convert disclaimers from JSON back to TEXT
    op.execute("""
        ALTER TABLE organizations 
        ALTER COLUMN disclaimers TYPE TEXT 
        USING CASE 
            WHEN disclaimers IS NULL THEN NULL
            ELSE disclaimers::text
        END
    """)
    # ### end Alembic commands ###
