"""Add has_completed_profile and student_guardian relationship

Revision ID: 90c0d19774ad
Revises: d632a32cb1fc
Create Date: 2025-10-27 20:26:12.385741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90c0d19774ad'
down_revision = 'd632a32cb1fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_guardians',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('guardian_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.Enum('primary', 'secondary', 'emergency', name='guardianrelationtype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['guardian_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'student_id', 'guardian_id', name='_org_student_guardian_uc')
    )
    op.add_column('profiles', sa.Column('has_completed_profile', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'has_completed_profile')
    op.drop_table('student_guardians')
    # ### end Alembic commands ###
