"""null in user_id for org_members for correct tracking

Revision ID: a8f04dce02fa
Revises: 573df1460576
Create Date: 2025-10-28 01:57:27.204768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8f04dce02fa'
down_revision = '573df1460576'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
