"""invitations table

Revision ID: cb4c5726f2f1
Revises: a8f04dce02fa
Create Date: 2025-10-28 16:42:25.233183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb4c5726f2f1'
down_revision = 'a8f04dce02fa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    from sqlalchemy.dialects import postgresql as pg
    
    org_role_enum = pg.ENUM(
        'admin', 'secretary', 'staff', 'guardian', 'student', 
        name='orgrole',
        create_type=False
    )
    
    invitation_status_enum = pg.ENUM(
        'pending', 'accepted', 'expired', 'cancelled', 
        name='invitationstatus',
        create_type=False
    )
    org_role_enum.create(op.get_bind(), checkfirst=True)
    invitation_status_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('invitations',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('organization_id', sa.UUID(), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        # sa.Column('role', org_role_enum, nullable=False),
        sa.Column('role', sa.String(), nullable=False),
        sa.Column('inviter_id', sa.UUID(), nullable=False),
        sa.Column('status', invitation_status_enum, nullable=False),
        sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('expires_at', sa.DateTime(timezone=True), server_default=sa.text("now() + '7 days'::interval"), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['inviter_id'], ['profiles.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invitations')
    
    invitation_status_enum = sa.Enum(
        'pending', 'accepted', 'expired', 'cancelled', 
        name='invitationstatus'
    )
    invitation_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
