"""updated org roles for users

Revision ID: d632a32cb1fc
Revises: 004fb2cd949f
Create Date: 2025-10-27 19:04:51.000986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd632a32cb1fc'
down_revision = '004fb2cd949f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
